- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: "{{gather}}"
  become: yes
  tasks:
  - name: find oldfile
    stat: path={{oldfile}}
    register: ofst
  - name: find backupdir
    stat: path={{backuppath}}
    register: bp
  - name: create backuppath if it not exists
    file: path={{backuppath}} state=directory group=admin owner=admin recurse=yes
    when: bp.stat.exists == False
  - name: backup extfiles 
    shell: zip -r {{backupfile}} {{oldfile}}
    when: ofst.stat.exists == True
  - name: create targetdir if it not exists
    file: path={{oldfile}} state=directory group=admin owner=admin recurse=yes
    when: ofst.stat.exists == False
  - name: unpack extfiles
    unarchive: src={{src}} dest={{dest}} group={{group}} owner={{owner}}
