- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: "{{gather}}"
  become: yes
  tasks:
  - name: tomcat stop
    service: name={{service}} pattern={{service_home}} state=stopped
  - name: find old-war
    stat: path={{old_warFile}}
    register: st
  - name: find backupdir
    stat: path={{backuppath}}
    register: bp
  - name: find old-file
    stat: path={{old_path}}
    register: of
  - name: create backuppath if it not exists
    file: path={{backuppath}} state=directory group=admin owner=admin recurse=yes
    when: bp.stat.exists == False
  - name: backup old-warFile
    copy: src={{old_warFile}} dest={{backup}} group=admin owner=admin remote_src=True
    when: st.stat.exists == True
  - name: delete old-file
    file: path={{old_path}} state=absent
    when: of.stat.exists == True
  - name: delete old-war
    file: path={{old_warFile}} state=absent
    when: st.stat.exists == True
  - name: copy pkg to pkgpath
    copy: src={{src}} dest={{dest}} group=admin owner=admin
  - name: tomcat start
    service: name={{service}} pattern={{service_home}} state=started
